---
- name: Add Vlan Pool
  aci_rest:
    hostname: '{{ aci_ip }}'
    username: '{{ aci_username }}'
    password: '{{ aci_password }}'
    validate_certs: no
    path: /api/node/mo/uni/infra/vlanns-[{{ item.access_policy_vlan_pool_name }}]-{{ item.access_policy_vlan_pool_alloc }}.json
    method: post
    content:
      fvnsVlanInstP:
        attributes:
          allocMode: '{{ item.access_policy_vlan_pool_alloc }}'
          descr: ''
          dn: uni/infra/vlanns-[{{ item.access_policy_vlan_pool_name }}]-{{ item.access_policy_vlan_pool_alloc }}
          name: '{{ item.access_policy_vlan_pool_name }}'
  with_items: '{{ SSOT_fabric|aci_listify("access_policy","vlan_pool") }}'

