---
# 3.1.3 Create Attachable Entity Profile for each External Node

- name: Create Attachable Entity profile with an assigned physical domain
  aci_rest:
    hostname: "{{ aci_ip }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: no
    path: /api/node/mo/uni/infra.json    # path to the attachable entity profile object
    method: "{{'post' if (item.access_policy_aep_state == 'present') else 'delete' }}"   
    content:
      infraAttEntityP:  # this is the attachable entity profile object
        attributes:
          name: "{{item.access_policy_aep_name}}"       # only the name attribute is needed to create the object
        children:
        - infraRsDomP:  # this object is the link to the physical domain we want to assign to our attacable entity profile
            attributes:  # Multiple domains can be assigned at once to a single EPG if configured in the fabric.yml file
              tDn: "uni/{{item.access_policy_aep_domain_name}}"   # this tDn attribute contains the link to the physical domain object

  with_items: "{{ SSOT_fabric|aci_listify('access_policy','aep', 'domain') }}"
