---
- name: Create EPG
  aci_epg:
    hostname: '{{ aci_ip }}'
    username: '{{ aci_username }}'
    password: '{{ aci_password }}'
    validate_certs: no
    tenant: "{{ item.tenant_name }}"
    ap: "{{ item.tenant_app_name }}"
    epg: "{{ item.tenant_app_epg_name }}"
    bd: "{{ item.tenant_app_epg_bd }}"
  with_items:
    - '{{ SSOT_tenant|aci_listify("tenant","app","epg") }}'

