
#### Type of contract associations

provider_case:
  - url: api/node/mo/uni/tn-{{ item.tenant_name }}/out-{{ item.tenant_external_routed_network_name }}/instP-{{item.tenant_external_routed_network_epg_name}}/rsprov-{{ item.tenant_external_routed_network_epg_associate_contracts_name }}.json
    state:  "{{item.tenant_external_routed_network_epg_associate_contracts_state}}"
    payload:
       fvRsProv:
         attributes:
            matchT: '{{ item.tenant_external_routed_network_epg_associate_contracts_matchType }}'
            tnVzBrCPName: '{{ item.tenant_external_routed_network_epg_associate_contracts_name }}'


consumer_case:
   - url: api/node/mo/uni/tn-{{ item.tenant_name }}/out-{{ item.tenant_external_routed_network_name }}/instP-{{item.tenant_external_routed_network_epg_name}}.json
     state:  "{{item.tenant_external_routed_network_epg_associate_contracts_state}}"
     payload:
         fvRsCons:
             attributes:
               tnVzBrCPName: '{{ item.tenant_external_routed_network_epg_associate_contracts_name }}'


