action: create
method: '{{ "post" if (action == "create") else "delete" }}'
state: '{{ "present" if (method == "post") else "absent" }}'


#### Type of contract associations

provider_case:
  - url: api/node/mo/uni/tn-{{ item.tenant_name }}/out-{{ item.tenant_external_routed_network_name }}/instP-{{item.tenant_external_routed_network_epg_name}}/rsprov-{{ item.tenant_external_routed_network_epg_associate_contracts_name }}.json
    payload:
       fvRsProv:
         attributes:
            matchT: '{{ item.tenant_external_routed_network_epg_associate_contracts_matchType }}'
            tnVzBrCPName: '{{ item.tenant_external_routed_network_epg_associate_contracts_name }}'


consumer_case:
   - url: api/node/mo/uni/tn-{{ item.tenant_name }}/out-{{ item.tenant_external_routed_network_name }}/instP-{{item.tenant_external_routed_network_epg_name}}.json
     payload:
         fvRsCons:
             attributes:
               tnVzBrCPName: '{{ item.tenant_external_routed_network_epg_associate_contracts_name }}'


