---
#3.4.1.6 Assign Match-all Contract as Consumed Contract to the External Network/EPG

- name: Create appropriate payload based on the Contract Mode 
  set_fact:
    array_content: "{{ provider_case if (item.tenant_external_routed_network_epg_associate_contracts_mode == 'provider') else consumer_case }}" 
    #chooses different content depending on whether it's a consumed or provided contract 
  with_items: 
    - "{{ SSOT_tenant|aci_listify('tenant','external_routed_network','epg','associate_contracts') }}"
  register: array_of_contents

- name: Create a list where each cell is an appropriate payload
  set_fact: 
       data_struc: "{{ array_of_contents.results | map(attribute='ansible_facts.array_content') | list }}"

- name: Associate ( if not already associated ) Contracts to external EPGs
  aci_rest:
    hostname: "{{ aci_ip }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: no
    path: "{{ item[0].url }}"
    method: "{{ 'post' if ( item[0].state == 'present') else 'delete' }}"
    content: "{{ item[0].payload }}"
  with_items: 
     - "{{ data_struc }}"



