---
# 3.1.5.1 Create Access Port Policy Group

- name: Create an access port policy group
  aci_rest:
    hostname: "{{ aci_ip }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: no
    path: api/node/mo/uni/infra/funcprof/accportgrp-{{ item.access_policy_interface_policy_policy_group_access_name }}.json #path to the Access Port Policy Group object
    method: "{{ 'post' if ( item.access_policy_interface_policy_policy_group_access_state == 'present' ) else 'delete' }}"
    content: 
        infraAccPortGrp:  #Access Port Policy Group object itself
            attributes:
                name: "{{ item.access_policy_interface_policy_policy_group_access_name }}"   
            children:
                - infraRsHIfPol:
                    attributes:
                        tnFabricHIfPolName: "{{ item.access_policy_interface_policy_policy_group_access_linklevel }}" #Link-Level Policy name to be associated to this group policy
                - infraRsCdpIfPol:
                    attributes:
                        tnCdpIfPolName: "{{ item.access_policy_interface_policy_policy_group_access_cdp }}" #CDP Policy name to be associated to this group policy
                - infraRsQosIngressDppIfPol:
                    attributes:
                        tnQosDppPolName: "{{ item.access_policy_interface_policy_policy_group_access_ingress }}" #Ingress Data Plan Policing Policy name to be associated to this group policy
                - infraRsMonIfInfraPol:
                    attributes:
                        tnMonInfraPolName: "{{ item.access_policy_interface_policy_policy_group_access_mon }}" # Monitoring Policy name to be associated to this group policy
                - infraRsQosPfcIfPol:
                    attributes:
                        tnQosPfcIfPolName: "{{ item.access_policy_interface_policy_policy_group_access_prioFlow }}" #Priority Flow Control Policy name to be associated to this group policy
                - infraRsFcIfPol:
                    attributes:
                        tnFcIfPolName: "{{ item.access_policy_interface_policy_policy_group_access_fibreChannel }}" #Fiber Channel Interface Policy name to be associated to this group policy
                - infraRsQosSdIfPol:
                    attributes:
                        tnQosSdIfPolName: "{{ item.access_policy_interface_policy_policy_group_access_slowDrain }}" #Slow Drain Policy name to be associated to this group policy
                - infraRsMcpIfPol:
                    attributes:
                        tnMcpIfPolName: "{{ item.access_policy_interface_policy_policy_group_access_mcp }}" # MCP Policy name to be associated to this group policy
                - infraRsLldpIfPol:
                    attributes:
                        tnLldpIfPolName: "{{ item.access_policy_interface_policy_policy_group_access_lldp }}" #LLDP Policy name to be associated to this group policy
                - infraRsStpIfPol:
                    attributes:
                        tnStpIfPolName: "{{ item.access_policy_interface_policy_policy_group_access_stp }}" #STP Interface Policy name to be associated to this group policy
                - infraRsAttEntP:
                    attributes:
                        tDn: uni/infra/attentp-{{ item.access_policy_interface_policy_policy_group_access_attEnt }} #Attached Entity Profile name to be associated to this group policy
                - infraRsStormctrlIfPol:
                    attributes:
                        tnStormctrlIfPolName: "{{ item.access_policy_interface_policy_policy_group_access_stormcontrol }}" #Storm Control Interface Policy name to be associated to this group policy
                - infraRsL2IfPol:
                    attributes:
                        tnL2IfPolName: "{{ item.access_policy_interface_policy_policy_group_access_l2 }}" #L2 Conrol Interface Policy name to be associated to this group policy
                - infraRsL2PortSecurityPol:
                    attributes:
                        tnL2PortSecurityPolName: "{{ item.access_policy_interface_policy_policy_group_access_portsecurity }}" # Port security Policy  name to be associated to this group policy
                - infraRsQosEgressDppIfPol:
                    attributes:
                        tnQosDppPolName: "{{ item.access_policy_interface_policy_policy_group_access_egress }}" # Egress Data Plane Policing Policy
                                                            
  with_items: 
    - "{{ SSOT_fabric|aci_listify('access_policy','interface_policy_policy_group_access') }}"
