---
- name: Create Logical Node Profile
  aci_rest:
    hostname: '{{ aci_ip }}'
    username: '{{ aci_username }}'
    password: '{{ aci_password }}'
    validate_certs: no
    path: /api/node/mo/uni/infra/nprof-{{ item.access_policy_switch_policy_profile_name }}.json
    method: post
    content:
      infraNodeP:
        attributes:
          descr: ''
          dn: uni/infra/nprof-{{item.access_policy_switch_policy_profile_name }}
          name: '{{ item.access_policy_switch_policy_profile_name }}'
  with_items: '{{ SSOT_fabric|aci_listify("access_policy","switch_policy_profile") }}'
