---
- name: Create L4 L7 Device Consumer
  aci_rest:
    hostname: '{{ aci_ip }}'
    username: '{{ aci_username }}'
    password: '{{ aci_password }}'
    validate_certs: "no"
    path: /api/node/mo/uni/tn-{{item.tenant_name}}/AbsGraph-{{item.tenant_L4_L7_devices_service_graph_template_name}}/AbsTermNodeCon-{{item.tenant_L4_L7_devices_service_graph_template_term_node_conn_name}}.json
    method:  "{{ 'post' if ( item.tenant_L4_L7_devices_service_graph_template_term_node_conn_state == 'present') else 'delete' }}"
    content:
      vnsAbsTermNodeCon:
        attributes:
          dn: uni/tn-{{item.tenant_name}}/AbsGraph-{{item.tenant_L4_L7_devices_service_graph_template_name}}/AbsTermNodeCon-{{item.tenant_L4_L7_devices_service_graph_template_term_node_conn_name}}
          name: "{{item.tenant_L4_L7_devices_service_graph_template_term_node_conn_name}}"
        children:
        - vnsAbsTermConn:
            attributes:
              dn: uni/tn-{{item.tenant_name}}/AbsGraph-{{item.tenant_L4_L7_devices_service_graph_template_name}}/AbsTermNodeCon-{{item.tenant_L4_L7_devices_service_graph_template_term_node_conn_name}}/AbsTConn
              name: '1'

  with_items: 
    - '{{ SSOT_tenant|aci_listify("tenant","L4_L7_devices","service_graph_template","term_node_conn") }}'


