---
- name: Create L4 L7 Device SG Template
  aci_rest:
    hostname: '{{ aci_ip }}'
    username: '{{ aci_username }}'
    password: '{{ aci_password }}'
    validate_certs: 'no'
    path: /api/node/mo/uni/tn-{{item.tenant_name}}/AbsGraph-{{item.tenant_L4_L7_devices_service_graph_template_name}}.json
    method:  "{{ 'post' if ( item.tenant_L4_L7_devices_service_graph_template_state == 'present') else 'delete' }}"
    content:
      vnsAbsGraph:
        attributes:
          dn: uni/tn-{{item.tenant_name}}/AbsGraph-{{item.tenant_L4_L7_devices_service_graph_template_name}}
          name: "{{item.tenant_L4_L7_devices_service_graph_template_name}}"
  with_items: 
    - '{{ SSOT_tenant|aci_listify("tenant","L4_L7_devices","service_graph_template") }}'


