---
# 3.1.4.2 Create CDP Policy

- name: Create a CDP policy
  aci_rest:
    hostname: "{{ aci_ip }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: no
    path: api/node/mo/uni/infra/cdpIfP-{{ item.access_policy_interface_policy_cdp_name }}.json  # Path to the CDP object
    method: "{{ 'post' if (item.access_policy_interface_policy_cdp_state == 'present') else 'delete' }}"
    content: 
        cdpIfPol: #CDP policy object itself
            attributes:
               name: "{{ item.access_policy_interface_policy_cdp_name }}"    
               adminSt: "{{ item.access_policy_interface_policy_cdp_adminSt }}"  #Admin State setting, can be enabled or disabled
  with_items: 
    - "{{ SSOT_fabric|aci_listify('access_policy','interface_policy_cdp') }}"

