---
- name: Print IP, USR, PASS for debug purposes. is group vars working here?
  debug: 
    msg: "DBG = {{ aci_ip }} _ {{ aci_username }} _ {{ aci_password }} "

- name: Item debug
  debug: 
    msg: "DBG_ITEM = {{ item }}"
  with_items:
     - '{{ SSOT_tenant|aci_listify("tenant","contract") }}'

- name: Deploy a contract with match all subject
  aci_rest:
    hostname: '{{ aci_ip }}'
    username: '{{ aci_username }}'
    password: '{{ aci_password }}'
    validate_certs: no
    path: api/node/mo/uni/tn-{{ item.tenant_name }}/brc-{{ item.tenant_contract_name }}.json
    method: post
    content: 
        vzBrCP:
            attributes:
               name: "{{ item.tenant_contract_name }}"
               scope: "{{ item.tenant_contract_scope }}"
            children:
                - vzSubj:
                    attributes:
                        name: "{{ item.tenant_contract_name }}_match_all_subject"
                    children:
                        - vzRsSubjFiltAtt:
                             attributes:
                                tnVzFilterName: "{{ item.tenant_contract_name }}_match_all_filter"
  with_items: 
    - '{{ SSOT_tenant|aci_listify("tenant","contract") }}'
