---
# STEPS TO DEPLOY A 'MATCH-ALL' CONTRACT:
# 1- CHECK IF FILTER IS PRENSENT, IF YES SKIP CREATION ELSE CREATE IT AND CREATE A NEW ENTRY TOO
# 2- IN CASE FILTER EXISTS CHECK FOR ENTRY, IF NOT PRESENT CREATE IT ELSE SKIP CREATION
# 3- CHECK IF SUBJECT IS PRENSENT, IF YES SKIP CREATION BUT CHECK FOR SUBJECT TO CONTRACT ASSOCIATION ELSE CREATE IT
# 4- IF SUBJECT IS NOT ASSOCIATED WITH CONTRACT, DO ASSOCIATE IT
# 5- CHECK IF CONTRACT IS PRENSENT, IF YES SKIP CREATION ELSE CREATE IT

###############  Filter part

- name: Create ( if not already present ) a match-all Filter
  aci_filter:
    hostname: '{{ aci_ip }}'
    username: '{{ aci_username }}'
    password: '{{ aci_password }}'
    filter: "{{ item.tenant_contract_name }}_match_all_filter"
    description: 'Filter for {{ item.tenant_contract_name }} to implement match-all policy'
    tenant: '{{ item.tenant_name }}'
    state: '{{ state }}'
    validate_certs: no
  with_items: 
    - '{{ SSOT_tenant|aci_listify("tenant","contract") }}'

- name: Create ( if not already present ) Filter Entry for Match-all Filter
  aci_filter_entry:
    hostname: '{{ aci_ip }}'
    username: '{{ aci_username }}'
    password: '{{ aci_password }}'
    entry: "{{ item.tenant_contract_name }}_match_all_entry_filter"
    tenant: '{{ item.tenant_name }}'
    ether_type: 'unspecified'
    filter: "{{ item.tenant_contract_name }}_match_all_filter"
    description: 'Filter Entry for {{ item.tenant_contract_name }} to implement match-all policy'
    validate_certs: no
    state: '{{ state }}'
  with_items: 
    - '{{ SSOT_tenant|aci_listify("tenant","contract") }}'

###############  Contract part

- name: Create ( if not already present ) Contracts
  aci_contract:
    hostname: '{{ aci_ip }}'
    username: '{{ aci_username }}'
    password: '{{ aci_password }}'
    contract: '{{ item.tenant_contract_name }}'
    description: 'match-all contract created by Ansible'
    tenant: '{{ item.tenant_name }}'
    scope: '{{ item.tenant_contract_scope }}'
    validate_certs: no
    state: '{{ state }}' # this flag makes sure to create contracts ONLY if not already presents
  with_items: 
    - '{{ SSOT_tenant|aci_listify("tenant","contract") }}'


- name: Create the subject and associate to contract
  aci_contract_subject:
    hostname: '{{ aci_ip }}'
    username: '{{ aci_username }}'
    password: '{{ aci_password }}'
    tenant: '{{ item.tenant_name }}'
    contract: '{{ item.tenant_contract_name }}'
    subject: "{{ item.tenant_contract_name }}_match_all_subject"
    dscp: unspecified
    state: '{{ state }}'
    validate_certs: no
  with_items: 
    - '{{ SSOT_tenant|aci_listify("tenant","contract") }}'

- name: Associate filter to subject 
  aci_contract_subject_to_filter:
    hostname: '{{ aci_ip }}'
    username: '{{ aci_username }}'
    password: '{{ aci_password }}'
    tenant: '{{ item.tenant_name }}'
    contract: '{{ item.tenant_contract_name }}'
    subject: "{{ item.tenant_contract_name }}_match_all_subject"
    filter: "{{ item.tenant_contract_name }}_match_all_filter"
    state: '{{ state }}'
    validate_certs: no
  with_items: 
    - '{{ SSOT_tenant|aci_listify("tenant","contract") }}'
