---
- name: Assign nodes to Logical Node Profiles
  aci_rest:
    hostname: '{{ aci_ip }}'
    username: '{{ aci_username }}'
    password: '{{ aci_password }}'
    validate_certs: no
    path: /api/node/mo/uni/infra/nprof-{{ item.access_policy_switch_policy_profile_name }}.json
    method: post
    content:
      infraNodeP:
        attributes:
          descr: ''
          dn: uni/infra/nprof-{{ item.access_policy_switch_policy_profile_name }}
          name: '{{ item.access_policy_switch_policy_profile_name }}'
          ownerKey: ''
          ownerTag: ''
        children:
        - infraLeafS:
            attributes:
              descr: ''
              name: '{{ item.access_policy_switch_policy_profile_leaf_selector_name }}'
              ownerKey: ''
              ownerTag: ''
              type: range
            children:
            - infraNodeBlk:
                attributes:
                  descr: ''
                  from: '{{ item.access_policy_switch_policy_profile_leaf_selector_from }}'
                  name: '{{ item.access_policy_switch_policy_profile_leaf_selector_name }}'
                  to: '{{ item.access_policy_switch_policy_profile_leaf_selector_to }}'
  with_items: '{{ SSOT_fabric|aci_listify("access_policy","switch_policy_profile","leaf_selector") }}'

