---
# 3.1.4.5 Create an STP interface policy

- name: Create an interface STP policy
  aci_rest:
    hostname: "{{ aci_ip }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: no
    path: api/node/mo/uni/infra/ifPol-{{ item.access_policy_interface_policy_stp_name}}.json  #path to the STP interface policy object
    method: "{{ 'post' if ( item.access_policy_interface_policy_stp_state == 'present' ) else 'delete' }}"
    content: 
        stpIfPol: # STP interface policy object itself
            attributes:
               name: "{{ item.access_policy_interface_policy_stp_name }}"  # Name of the STP Interface Policy  
               ctrl: "{{ item.access_policy_interface_policy_stp_ctrl }}"   # Interface controls, such as BPDU Guard enabled (bpdu-guard) 
  with_items: 
    - "{{ SSOT_fabric|aci_listify('access_policy','interface_policy_stp') }}"

