---
## Input variables from Rundeck
# SSoT_path
# aci_ip
# aci_username
# aci_password
# tenant_name
# exteral_routed_network
# logical_node_profile

- name: Create logical node profile 
  hosts: "{{ target }}"
  gather_facts: no
  tasks:
    - include_vars:
        file: "{{ ACI_SSoT_path }}/{{ tenant_name }}.yml"
        name: SSOT_tenant

      # Intent Statement
    - include_role:
        name: aci-logical-node-profile

