---
## Input variables from Rundeck
# ACI_SSoT_path
# aci_ip
# aci_username
# aci_password
# tenant_name

# 3.2.2.1 Create ACI Bridge domain and Assign Private Network
- name: Create BD and Assign VRF
  hosts: "{{ target }}"
  gather_facts: no

  tasks:
    - include_vars:
        file: "{{ ACI_SSoT_path }}/{{ tenant_name }}.yml"
        name: SSOT_tenant

    # Intent Statement
    - include_role:
        name: aci-tenant-bd

