---

#3.4.1.4.1 Create External Network (EPG) for the External Routed Network

- name: Create External Network (EPG) for the External Routed Network
  aci_rest:
    hostname: "{{ aci_ip }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: no
    path: api/node/mo/uni/tn-{{ item.tenant_name }}/out-{{ item.tenant_external_routed_network_name }}/instP-{{item.tenant_external_routed_network_epg_name}}.json  #path to the EPG object
    method:  "{{ 'post' if ( item.tenant_external_routed_network_epg_state == 'present') else 'delete' }}"  
    content: 
        l3extInstP: #External routed network"s EPG object
            attributes:
               name: "{{item.tenant_external_routed_network_epg_name}}"
           
  with_items: 
    - "{{ SSOT_tenant|aci_listify('tenant','external_routed_network','epg') }}"
