---
## Input variables from Rundeck
# SSoT_path
# aci_ip
# aci_username
# aci_password
# tenant_name
# vrf_name


- name: Create Physical Domain
  hosts: "{{ target }}"
  gather_facts: no
  tasks:
    - include_vars:
        file: "{{ ACI_SSoT_path }}/fabric.yml"
        name: SSOT_fabric

      # Intent Statement
      - include_role:
          name: aci-vlan-pool
      - include_role:
          name: aci-physical-domain

