---
## Input variables from Rundeck
# ACI_SSoT_path
# aci_ip
# aci_username
# aci_password
# tenant_name


#3.2.2.3 Create ACI EPG according Security Zone definition per each Class.
- name: Create L4 l7 Service Graph Template
  hosts: "{{ target }}"
  gather_facts: no

  tasks:
    - include_vars:
        file: "{{ ACI_SSoT_path }}/{{ tenant_name }}.yml"
        name: SSOT_tenant

    # Intent Statement
    - include_role:
        name: aci-L4-L7-service-graph-template

