---
## Input variables from Rundeck
# SSoT_path
# aci_ip
# aci_username
# aci_password
# tenant_name

- name: CREATE EXTERNAL EPG, MATCH ALL CONTRACT, ASSOCIATE THEM
  hosts: "{{ target }}"
  gather_facts: no

  tasks:
    - include_vars:
        file: "{{ ACI_SSoT_path }}/{{ tenant_name }}.yml"
        name: SSOT_tenant

    # SUB-TASKS
    - include_role:
         name: aci-create-extr-epg
    - include_role:
         name: aci-associate-subnet-to-epg
    - include_role:
         name: aci-create-match-all-contract
    - include_role:
         name: aci-associate-contract-to-extr-epg
