# 3.4.1.2  Prepare Primary External Node
# This playbook can be used alone or can be used as part of a bigger playbook(e.g.: pb-aci-connectivity-sr-firewall)
### This playbook creates Logial Node profiles (for the primary node) and estabilish a BGP Peer Connectivity to External EPG
 
---
- name: Prepare Primary External Node
  hosts: "{{ target }}"
  gather_facts: no

  tasks:
    - include_vars:
        file: "{{ ACI_SSoT_path }}/{{ tenant_name }}.yml"
        name: SSOT_tenant

    # 3.4.1.2.1 Create Logical Node Profile and assign Nodes
    - include_role:
         name: aci-logical-node-profile
    
    # 3.4.1.2.2 Create Logical Interface Profile and assign Interfaces
    - include_role:
         name: aci-external-network-logical-interface

    # 3.6.1.3.2.1 Create Static Route for All configured nodes in a certain Logical Node Profile
    - include_role:
         name: aci-create-static-route-nodes
    
    # 3.4.1.2.3 Create Peer connectivity profile
    - include_role:
         name: aci-external-network-peer-conn-profile

    - include_role:
         name: aci-create-bfd-profile
         
    # 3.4.1.2.4 Verify BGP Peering    
    - include_role:
         name: aci-verify-bgp-peering
