---

# 3.1.4 Create Interface Policies for each External Node
# This playbook creates the interface policies for LLDP, CDP, STP, Port-Channel and Link-Level
# Keep in mind that multiple interfaces of the same type of policy can be created at once, as long as 
# they're defined in the fabric file. For example:
# - interface_policy_cdp:
#   - name: test_cdp1
#     adminSt: disabled
#   - name: test_cdp2
#     adminSt: disabled
#   - name: test_cdp3
#     adminSt: enabled

- name: Create Interface Policies
  hosts: "{{ target }}"
  gather_facts: no

  tasks:
    - include_vars:
        file: "{{ ACI_SSoT_path }}/fabric.yml"
        name: SSOT_fabric

    # 3.1.4.1 Create Link Level Policy
    - include_role:
         name: aci-create-link-level-policy
    # 3.1.4.2 Create CDP Policy
    - include_role:
         name: aci-create-cdp-policy
    # 3.1.4.3 Create LLDP Interface Policy
    - include_role:
         name: aci-create-lldp-policy
    # 3.1.4.4 Create Port-Channel Policies
    - include_role:
         name: aci-create-port-channel-policy
    # 3.1.4.5 Create STP Interface Policy
    - include_role:
         name: aci-create-stp-policy
