---

#3.1.3 Create Attachable Entity Profile for each External Node. 
# It's assumed that the VLAN Pools already exist

- name: Create Attachable Entity Profile
  hosts: "{{ target }}"
  gather_facts: no

  tasks:
    - include_vars:
        file: "{{ ACI_SSoT_path }}/fabric.yml"
        name: SSOT_fabric

    - include_role:
         name: aci-aep
