---

# 3.1.6 Create Interface profile

- name: Create Interface Profile
  hosts: "{{ target }}"
  gather_facts: no

  tasks:
    - include_vars:
        file: "{{ ACI_SSoT_path }}/fabric.yml"
        name: SSOT_fabric

    # 3.1.6.1-3 Create Interface Profile for Access Port or PC/vPC
    - include_role:
         name: aci-create-interface-profile


