---
# 3.4.1.4.2 Create Subnet for the External Routed Network
# This role deploys a subnet under a specified External Network (EPG)

- name: Deploy an Subnet under a specified External EPG 
  aci_rest:
    hostname: "{{ aci_ip }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: no
    path: api/node/mo/uni/tn-{{ item.tenant_name }}/out-{{ item.tenant_external_routed_network_name }}/instP-{{item.tenant_external_routed_network_epg_name}}/extsubnet-[{{item.tenant_external_routed_network_epg_subnets_ip}}/{{item.tenant_external_routed_network_epg_subnets_mask}}].json
    method: "{{ 'post' if ( item.tenant_external_routed_network_epg_subnets_state == 'present') else 'delete' }}"   
    content: 
        l3extSubnet:  #EPG subnet object itself
            attributes:
               ip: "{{item.tenant_external_routed_network_epg_subnets_ip}}/{{item.tenant_external_routed_network_epg_subnets_mask}}" 
               #ip address/mask of the subnet
               aggregate: "{{item.tenant_external_routed_network_epg_subnets_aggregate}}" #aggregate flags
               scope: "{{item.tenant_external_routed_network_epg_subnets_scope}}" #subnet scope flags
           
  with_items: 
    - "{{ SSOT_tenant|aci_listify('tenant','external_routed_network','epg','subnets') }}"
