---
- name: Print IP, USR, PASS for debug purposes. is group vars working here?
  debug: 
    msg: "DBG = {{ aci_ip }} _ {{ aci_username }} _ {{ aci_password }} "
  when: debug == "true"

- name: Item debug
  debug: 
    msg: "DBG_ITEM = {{ item }}"
  with_items:
     - '{{ SSOT_tenant|aci_listify("tenant","external_routed_network","epg","subnets")}}'
  when: debug == "true"

- name: Deploy an Subnet under a specified External EPG 
  aci_rest:
    hostname: '{{ aci_ip }}'
    username: '{{ aci_username }}'
    password: '{{ aci_password }}'
    validate_certs: no
    path: api/node/mo/uni/tn-{{ item.tenant_name }}/out-{{ item.tenant_external_routed_network_name }}/instP-{{item.tenant_external_routed_network_epg_name}}/extsubnet-[{{item.tenant_external_routed_network_epg_subnets_ip}}/{{item.tenant_external_routed_network_epg_subnets_mask}}].json
    method: '{{ method }}'
    content: 
        l3extSubnet:
            attributes:
               ip: '{{item.tenant_external_routed_network_epg_subnets_ip}}/{{item.tenant_external_routed_network_epg_subnets_mask}}'
               aggregate: '{{item.tenant_external_routed_network_epg_subnets_aggregate}}'
               scope: '{{item.tenant_external_routed_network_epg_subnets_scope}}'
           
  with_items: 
    - '{{ SSOT_tenant|aci_listify("tenant","external_routed_network","epg","subnets") }}'
