---
# 3.1.4.4 Create Port-Channel Policy

- name: Create a Port-Channel policy
  aci_rest:
    hostname: "{{ aci_ip }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: no
    path: api/node/mo/uni/infra/lacplagp-{{item.access_policy_interface_policy_port_channel_name}}.json  #path to the port-channel policy object
    method: "{{ 'post' if (item.access_policy_interface_policy_port_channel_state == 'present' ) else 'delete' }}"
    content: 
        lacpLagPol:  # port-channel policy object itself
            attributes:
               name: "{{item.access_policy_interface_policy_port_channel_name }}"
               mode: "{{item.access_policy_interface_policy_port_channel_mode }}"  # Port-channel policy mode, for example 'LACP Active'
               ctrl: "{{item.access_policy_interface_policy_port_channel_ctrl }}" # Control flags, such as Graceful Convergence (graceful-conv)
               minLinks: "{{item.access_policy_interface_policy_port_channel_minLinks }}" # minimum number of links
               maxLinks: "{{item.access_policy_interface_policy_port_channel_maxLinks }}"  # maximum number of links 
                    
  with_items: 
    - "{{ SSOT_fabric|aci_listify('access_policy','interface_policy_port_channel') }}"

